name: rewards_balance
description: Cloud Function to fetch user reward balances.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.4.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
